# This is a basic workflow to help you get started with Actions

name: Update Post from Notion

# Controls when the workflow will run
on:
  schedule:
    - cron: "30 14 * * 1-5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.14.2"

      # Install dependency
      - name: Install dependency with Yarn
        run: yarn install

      # Runs a set of commands using the runners shell
      - name: Run notion to blog script
        run: yarn notion2blog-start
        env:
          POST_DATABASE_ID: ${{secrets.POST_DATABASE_ID}}
          NOTION_CLIENT_KEY: ${{secrets.NOTION_CLIENT_KEY}}

      # Commit And Push
      - name: Commit changes & push
        run: |
          git config --global user.name 'action bot' 
          git add -A
          git commit -am "auto-update blog post from notion" --allow-empty
      - name: Push changes
        run: |
          git push
